name: reneDeploys
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        
      - name: posibleSolucion
        run: npm install --save-dev @babel/plugin-proposal-private-property-in-object

      - name: Install packages
        run: npm install
      
      - name: Build project
        run: |
          $env:CI = "false"
          npm run build

